"""Keelung City local official water adapters."""

from app.adapters.local_keelung.water import (
    DEFAULT_KEELUNG_WATER_TIMEOUT_SECONDS,
    KEELUNG_DATA_URL,
    KEELUNG_FLOOD_SENSOR_API_URL,
    KEELUNG_FLOOD_SENSOR_METADATA,
    KEELUNG_RAINFALL_API_URL,
    KEELUNG_RAINFALL_METADATA,
    KEELUNG_WATER_LEVEL_API_URL,
    KEELUNG_WATER_LEVEL_METADATA,
    FetchJson,
    KeelungFloodSensorApiAdapter,
    KeelungRainfallApiAdapter,
    KeelungWaterAdapterError,
    KeelungWaterFetchError,
    KeelungWaterLevelApiAdapter,
    KeelungWaterPayloadError,
    fetch_keelung_json,
    parse_keelung_flood_sensor_payload,
    parse_keelung_rainfall_payload,
    parse_keelung_water_level_payload,
)

__all__ = [
    "DEFAULT_KEELUNG_WATER_TIMEOUT_SECONDS",
    "KEELUNG_DATA_URL",
    "KEELUNG_FLOOD_SENSOR_API_URL",
    "KEELUNG_FLOOD_SENSOR_METADATA",
    "KEELUNG_RAINFALL_API_URL",
    "KEELUNG_RAINFALL_METADATA",
    "KEELUNG_WATER_LEVEL_API_URL",
    "KEELUNG_WATER_LEVEL_METADATA",
    "FetchJson",
    "KeelungFloodSensorApiAdapter",
    "KeelungRainfallApiAdapter",
    "KeelungWaterAdapterError",
    "KeelungWaterFetchError",
    "KeelungWaterLevelApiAdapter",
    "KeelungWaterPayloadError",
    "fetch_keelung_json",
    "parse_keelung_flood_sensor_payload",
    "parse_keelung_rainfall_payload",
    "parse_keelung_water_level_payload",
]
