"""Taipei City local official water adapters."""

from app.adapters.local_taipei.water import (
    DEFAULT_TAIPEI_WATER_TIMEOUT_SECONDS,
    TAIPEI_PUMP_STATION,
    TAIPEI_PUMP_STATION_API_URL,
    TAIPEI_PUMP_STATION_DATA_URL,
    TAIPEI_RIVER_WATER_LEVEL,
    TAIPEI_RIVER_WATER_LEVEL_API_URL,
    TAIPEI_RIVER_WATER_LEVEL_DATA_URL,
    TAIPEI_RIVER_WATER_LEVEL_METADATA_CSV_URL,
    TAIPEI_SEWER_WATER_LEVEL,
    TAIPEI_SEWER_WATER_LEVEL_API_URL,
    TAIPEI_SEWER_WATER_LEVEL_DATA_URL,
    TAIPEI_SEWER_WATER_LEVEL_METADATA_CSV_URL,
    FetchJson,
    FetchText,
    TaipeiPumpStationApiAdapter,
    TaipeiWaterAdapterError,
    TaipeiWaterFetchError,
    TaipeiWaterLevelApiAdapter,
    TaipeiWaterLevelSource,
    TaipeiWaterPayloadError,
    fetch_taipei_json,
    fetch_taipei_text,
    parse_taipei_pump_station_payload,
    parse_taipei_station_metadata_csv,
    parse_taipei_water_level_payload,
)

__all__ = [
    "DEFAULT_TAIPEI_WATER_TIMEOUT_SECONDS",
    "TAIPEI_PUMP_STATION",
    "TAIPEI_PUMP_STATION_API_URL",
    "TAIPEI_PUMP_STATION_DATA_URL",
    "TAIPEI_RIVER_WATER_LEVEL",
    "TAIPEI_RIVER_WATER_LEVEL_API_URL",
    "TAIPEI_RIVER_WATER_LEVEL_DATA_URL",
    "TAIPEI_RIVER_WATER_LEVEL_METADATA_CSV_URL",
    "TAIPEI_SEWER_WATER_LEVEL",
    "TAIPEI_SEWER_WATER_LEVEL_API_URL",
    "TAIPEI_SEWER_WATER_LEVEL_DATA_URL",
    "TAIPEI_SEWER_WATER_LEVEL_METADATA_CSV_URL",
    "FetchJson",
    "FetchText",
    "TaipeiPumpStationApiAdapter",
    "TaipeiWaterAdapterError",
    "TaipeiWaterFetchError",
    "TaipeiWaterLevelApiAdapter",
    "TaipeiWaterLevelSource",
    "TaipeiWaterPayloadError",
    "fetch_taipei_json",
    "fetch_taipei_text",
    "parse_taipei_pump_station_payload",
    "parse_taipei_station_metadata_csv",
    "parse_taipei_water_level_payload",
]
