"""CWA adapters."""

from app.adapters.cwa.heavy_rain_warning import (
    CWA_HEAVY_RAIN_CAP_URL,
    CWA_HEAVY_RAIN_WARNING_METADATA,
    DEFAULT_CWA_HEAVY_RAIN_TIMEOUT_SECONDS,
    CwaFetchCap,
    CwaHeavyRainWarningAdapter,
    CwaHeavyRainWarningAdapterError,
    CwaHeavyRainWarningConfigurationError,
    CwaHeavyRainWarningFetchError,
    CwaHeavyRainWarningRateLimitError,
    unresolved_cap_area_source_id,
)
from app.adapters.cwa.rainfall import (
    CWA_RAINFALL_API_URL,
    CWA_RAINFALL_DATA_GOV_DATASET_ID,
    CWA_RAINFALL_DATA_GOV_URL,
    CWA_RAINFALL_METADATA,
    DEFAULT_CWA_RAINFALL_TIMEOUT_SECONDS,
    CwaRainfallAdapter,
    CwaRainfallAdapterError,
    CwaRainfallApiAdapter,
    CwaRainfallConfigurationError,
    CwaRainfallFetchError,
    CwaRainfallPayloadError,
    FetchJson,
    parse_cwa_rainfall_api_payload,
)
from app.adapters.cwa.tide import (
    CWA_TIDE_LEVEL_API_URL,
    CWA_TIDE_LEVEL_DATASET_ID,
    CWA_TIDE_LEVEL_DATASET_URL,
    CWA_TIDE_LEVEL_METADATA,
    CWA_TIDE_LEVEL_STATION_API_URL,
    CWA_TIDE_LEVEL_STATION_DATASET_ID,
    CWA_TIDE_LEVEL_STATION_DATASET_URL,
    DEFAULT_CWA_TIDE_LEVEL_TIMEOUT_SECONDS,
    CwaTideLevelAdapter,
    CwaTideLevelAdapterError,
    CwaTideLevelApiAdapter,
    CwaTideLevelConfigurationError,
    CwaTideLevelFetchError,
    CwaTideLevelPayloadError,
    parse_cwa_tide_level_api_payload,
    parse_cwa_tide_station_metadata_payload,
)
from app.adapters.cwa.tide import (
    FetchJson as TideFetchJson,
)

__all__ = [
    "CWA_HEAVY_RAIN_CAP_URL",
    "CWA_HEAVY_RAIN_WARNING_METADATA",
    "CWA_RAINFALL_API_URL",
    "CWA_RAINFALL_DATA_GOV_DATASET_ID",
    "CWA_RAINFALL_DATA_GOV_URL",
    "CWA_RAINFALL_METADATA",
    "CWA_TIDE_LEVEL_API_URL",
    "CWA_TIDE_LEVEL_DATASET_ID",
    "CWA_TIDE_LEVEL_DATASET_URL",
    "CWA_TIDE_LEVEL_METADATA",
    "CWA_TIDE_LEVEL_STATION_API_URL",
    "CWA_TIDE_LEVEL_STATION_DATASET_ID",
    "CWA_TIDE_LEVEL_STATION_DATASET_URL",
    "DEFAULT_CWA_HEAVY_RAIN_TIMEOUT_SECONDS",
    "DEFAULT_CWA_RAINFALL_TIMEOUT_SECONDS",
    "DEFAULT_CWA_TIDE_LEVEL_TIMEOUT_SECONDS",
    "CwaFetchCap",
    "CwaHeavyRainWarningAdapter",
    "CwaHeavyRainWarningAdapterError",
    "CwaHeavyRainWarningConfigurationError",
    "CwaHeavyRainWarningFetchError",
    "CwaHeavyRainWarningRateLimitError",
    "CwaRainfallAdapter",
    "CwaRainfallAdapterError",
    "CwaRainfallApiAdapter",
    "CwaRainfallConfigurationError",
    "CwaRainfallFetchError",
    "CwaRainfallPayloadError",
    "CwaTideLevelAdapter",
    "CwaTideLevelAdapterError",
    "CwaTideLevelApiAdapter",
    "CwaTideLevelConfigurationError",
    "CwaTideLevelFetchError",
    "CwaTideLevelPayloadError",
    "FetchJson",
    "TideFetchJson",
    "parse_cwa_rainfall_api_payload",
    "parse_cwa_tide_level_api_payload",
    "parse_cwa_tide_station_metadata_payload",
    "unresolved_cap_area_source_id",
]
