"""CWA adapters."""

from app.adapters.cwa.rainfall import (
    CWA_RAINFALL_API_URL,
    CWA_RAINFALL_DATA_GOV_DATASET_ID,
    CWA_RAINFALL_DATA_GOV_URL,
    CWA_RAINFALL_METADATA,
    DEFAULT_CWA_RAINFALL_TIMEOUT_SECONDS,
    CwaRainfallAdapter,
    CwaRainfallApiAdapter,
    CwaRainfallAdapterError,
    CwaRainfallConfigurationError,
    CwaRainfallFetchError,
    CwaRainfallPayloadError,
    FetchJson,
    parse_cwa_rainfall_api_payload,
)
from app.adapters.cwa.tide import (
    CWA_TIDE_LEVEL_API_URL,
    CWA_TIDE_LEVEL_DATASET_ID,
    CWA_TIDE_LEVEL_DATASET_URL,
    CWA_TIDE_LEVEL_METADATA,
    CWA_TIDE_LEVEL_STATION_API_URL,
    CWA_TIDE_LEVEL_STATION_DATASET_ID,
    CWA_TIDE_LEVEL_STATION_DATASET_URL,
    DEFAULT_CWA_TIDE_LEVEL_TIMEOUT_SECONDS,
    CwaTideLevelAdapter,
    CwaTideLevelAdapterError,
    CwaTideLevelApiAdapter,
    CwaTideLevelConfigurationError,
    CwaTideLevelFetchError,
    CwaTideLevelPayloadError,
    FetchJson as TideFetchJson,
    parse_cwa_tide_level_api_payload,
    parse_cwa_tide_station_metadata_payload,
)

__all__ = [
    "CWA_RAINFALL_API_URL",
    "CWA_RAINFALL_DATA_GOV_DATASET_ID",
    "CWA_RAINFALL_DATA_GOV_URL",
    "CWA_RAINFALL_METADATA",
    "DEFAULT_CWA_RAINFALL_TIMEOUT_SECONDS",
    "CwaRainfallAdapter",
    "CwaRainfallApiAdapter",
    "CwaRainfallAdapterError",
    "CwaRainfallConfigurationError",
    "CwaRainfallFetchError",
    "CwaRainfallPayloadError",
    "FetchJson",
    "parse_cwa_rainfall_api_payload",
    "CWA_TIDE_LEVEL_API_URL",
    "CWA_TIDE_LEVEL_DATASET_ID",
    "CWA_TIDE_LEVEL_DATASET_URL",
    "CWA_TIDE_LEVEL_METADATA",
    "CWA_TIDE_LEVEL_STATION_API_URL",
    "CWA_TIDE_LEVEL_STATION_DATASET_ID",
    "CWA_TIDE_LEVEL_STATION_DATASET_URL",
    "DEFAULT_CWA_TIDE_LEVEL_TIMEOUT_SECONDS",
    "CwaTideLevelAdapter",
    "CwaTideLevelAdapterError",
    "CwaTideLevelApiAdapter",
    "CwaTideLevelConfigurationError",
    "CwaTideLevelFetchError",
    "CwaTideLevelPayloadError",
    "TideFetchJson",
    "parse_cwa_tide_level_api_payload",
    "parse_cwa_tide_station_metadata_payload",
]
