"""Taoyuan City local official water adapters."""

from app.adapters.local_taoyuan.water import (
    DEFAULT_TAOYUAN_WATER_TIMEOUT_SECONDS,
    TAOYUAN_FLOOD_SENSOR_API_URL,
    TAOYUAN_FLOOD_SENSOR_DATA_URL,
    TAOYUAN_FLOOD_SENSOR_METADATA,
    TAOYUAN_RAINFALL_API_URL,
    TAOYUAN_RAINFALL_DATA_URL,
    TAOYUAN_RAINFALL_METADATA,
    TAOYUAN_WATER_LEVEL_API_URL,
    TAOYUAN_WATER_LEVEL_DATA_URL,
    TAOYUAN_WATER_LEVEL_METADATA,
    FetchText,
    TaoyuanFloodSensorApiAdapter,
    TaoyuanRainfallApiAdapter,
    TaoyuanWaterAdapterError,
    TaoyuanWaterFetchError,
    TaoyuanWaterLevelApiAdapter,
    TaoyuanWaterPayloadError,
    fetch_taoyuan_text,
    parse_taoyuan_flood_sensor_xml,
    parse_taoyuan_rainfall_xml,
    parse_taoyuan_water_level_xml,
)

__all__ = [
    "DEFAULT_TAOYUAN_WATER_TIMEOUT_SECONDS",
    "TAOYUAN_FLOOD_SENSOR_API_URL",
    "TAOYUAN_FLOOD_SENSOR_DATA_URL",
    "TAOYUAN_FLOOD_SENSOR_METADATA",
    "TAOYUAN_RAINFALL_API_URL",
    "TAOYUAN_RAINFALL_DATA_URL",
    "TAOYUAN_RAINFALL_METADATA",
    "TAOYUAN_WATER_LEVEL_API_URL",
    "TAOYUAN_WATER_LEVEL_DATA_URL",
    "TAOYUAN_WATER_LEVEL_METADATA",
    "FetchText",
    "TaoyuanFloodSensorApiAdapter",
    "TaoyuanRainfallApiAdapter",
    "TaoyuanWaterAdapterError",
    "TaoyuanWaterFetchError",
    "TaoyuanWaterLevelApiAdapter",
    "TaoyuanWaterPayloadError",
    "fetch_taoyuan_text",
    "parse_taoyuan_flood_sensor_xml",
    "parse_taoyuan_rainfall_xml",
    "parse_taoyuan_water_level_xml",
]
