"""New Taipei City local official water adapters."""

from app.adapters.local_new_taipei.water import (
    DEFAULT_NEW_TAIPEI_WATER_TIMEOUT_SECONDS,
    NEW_TAIPEI_DATA_URL,
    NEW_TAIPEI_DRAINAGE_WATER_LEVEL_API_URL,
    NEW_TAIPEI_DRAINAGE_WATER_LEVEL_METADATA,
    NEW_TAIPEI_FLOOD_SENSOR_API_URL,
    NEW_TAIPEI_FLOOD_SENSOR_METADATA,
    NEW_TAIPEI_RAINFALL_API_URL,
    NEW_TAIPEI_RAINFALL_METADATA,
    NEW_TAIPEI_WATER_LEVEL_API_URL,
    NEW_TAIPEI_WATER_LEVEL_METADATA,
    FetchJson,
    NewTaipeiDrainageWaterLevelApiAdapter,
    NewTaipeiFloodSensorApiAdapter,
    NewTaipeiRainfallApiAdapter,
    NewTaipeiWaterAdapterError,
    NewTaipeiWaterFetchError,
    NewTaipeiWaterLevelApiAdapter,
    NewTaipeiWaterPayloadError,
    fetch_new_taipei_json,
    parse_new_taipei_drainage_water_level_payload,
    parse_new_taipei_flood_sensor_payload,
    parse_new_taipei_rainfall_payload,
    parse_new_taipei_water_level_payload,
)

__all__ = [
    "DEFAULT_NEW_TAIPEI_WATER_TIMEOUT_SECONDS",
    "NEW_TAIPEI_DATA_URL",
    "NEW_TAIPEI_DRAINAGE_WATER_LEVEL_API_URL",
    "NEW_TAIPEI_DRAINAGE_WATER_LEVEL_METADATA",
    "NEW_TAIPEI_FLOOD_SENSOR_API_URL",
    "NEW_TAIPEI_FLOOD_SENSOR_METADATA",
    "NEW_TAIPEI_RAINFALL_API_URL",
    "NEW_TAIPEI_RAINFALL_METADATA",
    "NEW_TAIPEI_WATER_LEVEL_API_URL",
    "NEW_TAIPEI_WATER_LEVEL_METADATA",
    "FetchJson",
    "NewTaipeiDrainageWaterLevelApiAdapter",
    "NewTaipeiFloodSensorApiAdapter",
    "NewTaipeiRainfallApiAdapter",
    "NewTaipeiWaterAdapterError",
    "NewTaipeiWaterFetchError",
    "NewTaipeiWaterLevelApiAdapter",
    "NewTaipeiWaterPayloadError",
    "fetch_new_taipei_json",
    "parse_new_taipei_drainage_water_level_payload",
    "parse_new_taipei_flood_sensor_payload",
    "parse_new_taipei_rainfall_payload",
    "parse_new_taipei_water_level_payload",
]
