"""WRA adapters."""

from app.adapters.wra.flood_incident import (
    DEFAULT_WRA_FLOOD_INCIDENT_TIMEOUT_SECONDS,
    WRA_FLOOD_INCIDENT_API_URL,
    WRA_FLOOD_INCIDENT_ATTRIBUTION,
    WRA_FLOOD_INCIDENT_DOCS_URL,
    WRA_FLOOD_INCIDENT_METADATA,
    WraFloodIncidentAdapterError,
    WraFloodIncidentApiAdapter,
    WraFloodIncidentConfigurationError,
    WraFloodIncidentFetchError,
    WraFloodIncidentFetchJson,
    WraFloodIncidentPayloadError,
    parse_wra_flood_incident_payload,
)

from app.adapters.wra.flood_warning import (
    DEFAULT_WRA_FLOOD_WARNING_TIMEOUT_SECONDS,
    WRA_FLOOD_WARNING_ATTRIBUTION,
    WRA_FLOOD_WARNING_DATA_GOV_DATASET_ID,
    WRA_FLOOD_WARNING_DATA_GOV_DATASET_IDS,
    WRA_FLOOD_WARNING_DATA_GOV_URL,
    WRA_FLOOD_WARNING_INDEX_URL,
    WRA_FLOOD_WARNING_KML_URLS,
    WRA_FLOOD_WARNING_METADATA,
    WraFloodWarningAdapter,
    WraFloodWarningAdapterError,
    WraFloodWarningFetchError,
    WraFloodWarningFetchJson,
    WraFloodWarningFetchText,
    WraFloodWarningPayloadError,
    WraFloodWarningRateLimitError,
    approved_wra_flood_warning_url,
    fetch_wra_flood_warning_json,
    fetch_wra_flood_warning_text,
    parse_wra_flood_warning_kml,
)
from app.adapters.wra.historical_flood import (
    DEFAULT_WRA_HISTORICAL_FLOOD_TIMEOUT_SECONDS,
    WRA_HISTORICAL_FLOOD_ATTRIBUTION,
    WRA_HISTORICAL_FLOOD_DATA_GOV_DATASET_ID,
    WRA_HISTORICAL_FLOOD_DATA_GOV_URL,
    WRA_HISTORICAL_FLOOD_INDEX_URL,
    WRA_HISTORICAL_FLOOD_METADATA,
    WraHistoricalFloodAdapter,
    WraHistoricalFloodAdapterError,
    WraHistoricalFloodFetchError,
    WraHistoricalFloodPayloadError,
    fetch_wra_historical_json,
    fetch_wra_historical_text,
    parse_wra_historical_flood_kml,
)
from app.adapters.wra.historical_flood import (
    FetchJson as HistoricalFetchJson,
)
from app.adapters.wra.historical_flood import (
    FetchText as HistoricalFetchText,
)
from app.adapters.wra.water_level import (
    DEFAULT_WRA_WATER_LEVEL_TIMEOUT_SECONDS,
    WRA_WATER_LEVEL_API_URL,
    WRA_WATER_LEVEL_DATA_GOV_DATASET_ID,
    WRA_WATER_LEVEL_DATA_GOV_URL,
    WRA_WATER_LEVEL_METADATA,
    WRA_WATER_STATION_API_URL,
    FetchJson,
    WraWaterLevelAdapter,
    WraWaterLevelAdapterError,
    WraWaterLevelApiAdapter,
    WraWaterLevelFetchError,
    WraWaterLevelPayloadError,
    parse_wra_station_metadata_payload,
    parse_wra_water_level_api_payload,
)

__all__ = [
    "DEFAULT_WRA_FLOOD_INCIDENT_TIMEOUT_SECONDS",
    "DEFAULT_WRA_FLOOD_WARNING_TIMEOUT_SECONDS",
    "DEFAULT_WRA_HISTORICAL_FLOOD_TIMEOUT_SECONDS",
    "DEFAULT_WRA_WATER_LEVEL_TIMEOUT_SECONDS",
    "WRA_FLOOD_INCIDENT_API_URL",
    "WRA_FLOOD_INCIDENT_ATTRIBUTION",
    "WRA_FLOOD_INCIDENT_DOCS_URL",
    "WRA_FLOOD_INCIDENT_METADATA",
    "WRA_FLOOD_WARNING_ATTRIBUTION",
    "WRA_FLOOD_WARNING_DATA_GOV_DATASET_ID",
    "WRA_FLOOD_WARNING_DATA_GOV_DATASET_IDS",
    "WRA_FLOOD_WARNING_DATA_GOV_URL",
    "WRA_FLOOD_WARNING_INDEX_URL",
    "WRA_FLOOD_WARNING_KML_URLS",
    "WRA_FLOOD_WARNING_METADATA",
    "WRA_HISTORICAL_FLOOD_ATTRIBUTION",
    "WRA_HISTORICAL_FLOOD_DATA_GOV_DATASET_ID",
    "WRA_HISTORICAL_FLOOD_DATA_GOV_URL",
    "WRA_HISTORICAL_FLOOD_INDEX_URL",
    "WRA_HISTORICAL_FLOOD_METADATA",
    "WRA_WATER_LEVEL_API_URL",
    "WRA_WATER_LEVEL_DATA_GOV_DATASET_ID",
    "WRA_WATER_LEVEL_DATA_GOV_URL",
    "WRA_WATER_LEVEL_METADATA",
    "WRA_WATER_STATION_API_URL",
    "FetchJson",
    "HistoricalFetchJson",
    "HistoricalFetchText",
    "WraFloodIncidentAdapterError",
    "WraFloodIncidentApiAdapter",
    "WraFloodIncidentConfigurationError",
    "WraFloodIncidentFetchError",
    "WraFloodIncidentFetchJson",
    "WraFloodIncidentPayloadError",
    "WraFloodWarningAdapter",
    "WraFloodWarningAdapterError",
    "WraFloodWarningFetchError",
    "WraFloodWarningFetchJson",
    "WraFloodWarningFetchText",
    "WraFloodWarningPayloadError",
    "WraFloodWarningRateLimitError",
    "WraHistoricalFloodAdapter",
    "WraHistoricalFloodAdapterError",
    "WraHistoricalFloodFetchError",
    "WraHistoricalFloodPayloadError",
    "WraWaterLevelAdapter",
    "WraWaterLevelAdapterError",
    "WraWaterLevelApiAdapter",
    "WraWaterLevelFetchError",
    "WraWaterLevelPayloadError",
    "approved_wra_flood_warning_url",
    "fetch_wra_flood_warning_json",
    "fetch_wra_flood_warning_text",
    "fetch_wra_historical_json",
    "fetch_wra_historical_text",
    "parse_wra_flood_warning_kml",
    "parse_wra_flood_incident_payload",
    "parse_wra_historical_flood_kml",
    "parse_wra_station_metadata_payload",
    "parse_wra_water_level_api_payload",
]
