INSERT INTO data_sources (
    name,
    adapter_key,
    source_type,
    license,
    update_frequency,
    health_status,
    legal_basis,
    is_enabled,
    metadata
)
VALUES
    (
        'Hsinchu County local FHY flood sensor observations',
        'local.hsinchu_county.flood_sensor',
        'official',
        'Government Open Data License',
        'near_realtime',
        'unknown',
        'L3',
        false,
        jsonb_build_object(
            'label_zh', '新竹縣地方淹水感測器',
            'owner_authority', 'Hsinchu County Government',
            'license_name', 'Government Open Data License',
            'tier', 'L3',
            'source_url', 'https://www.dprcflood.org.tw/SGDS/',
            'resource_url', 'https://www.dprcflood.org.tw/SGDS/WS/FHYBrokerWS.asmx/GetFHYFloodSensorInfoRt',
            'station_resource_url', 'https://www.dprcflood.org.tw/SGDS/WS/FHYBrokerWS.asmx/GetFHYFloodSensorStationByCityCode',
            'city_code', 10004,
            'supplier_filter', '新竹縣政府',
            'notes', 'Disabled by default; reads public FHY broker realtime rows joined to CityCode 10004 station metadata, keeping only Supplier=新竹縣政府.',
            'review_status', 'ready',
            'phase', 'local_realtime_sources'
        )
    ),
    (
        'Miaoli local FHY flood sensor observations',
        'local.miaoli.flood_sensor',
        'official',
        'Government Open Data License',
        'near_realtime',
        'unknown',
        'L3',
        false,
        jsonb_build_object(
            'label_zh', '苗栗縣地方淹水感測器',
            'owner_authority', 'Miaoli County Government',
            'license_name', 'Government Open Data License',
            'tier', 'L3',
            'source_url', 'https://www.dprcflood.org.tw/SGDS/',
            'resource_url', 'https://www.dprcflood.org.tw/SGDS/WS/FHYBrokerWS.asmx/GetFHYFloodSensorInfoRt',
            'station_resource_url', 'https://www.dprcflood.org.tw/SGDS/WS/FHYBrokerWS.asmx/GetFHYFloodSensorStationByCityCode',
            'city_code', 10005,
            'supplier_filter', '苗栗縣政府',
            'notes', 'Disabled by default; reads public FHY broker realtime rows joined to CityCode 10005 station metadata, keeping only Supplier=苗栗縣政府.',
            'review_status', 'ready',
            'phase', 'local_realtime_sources'
        )
    ),
    (
        'Changhua local FHY flood sensor observations',
        'local.changhua.flood_sensor',
        'official',
        'Government Open Data License',
        'near_realtime',
        'unknown',
        'L3',
        false,
        jsonb_build_object(
            'label_zh', '彰化縣地方淹水感測器',
            'owner_authority', 'Changhua County Government',
            'license_name', 'Government Open Data License',
            'tier', 'L3',
            'source_url', 'https://www.dprcflood.org.tw/SGDS/',
            'resource_url', 'https://www.dprcflood.org.tw/SGDS/WS/FHYBrokerWS.asmx/GetFHYFloodSensorInfoRt',
            'station_resource_url', 'https://www.dprcflood.org.tw/SGDS/WS/FHYBrokerWS.asmx/GetFHYFloodSensorStationByCityCode',
            'city_code', 10007,
            'supplier_filter', '彰化縣政府',
            'notes', 'Disabled by default; reads public FHY broker realtime rows joined to CityCode 10007 station metadata, keeping only Supplier=彰化縣政府.',
            'review_status', 'ready',
            'phase', 'local_realtime_sources'
        )
    ),
    (
        'Pingtung local FHY flood sensor observations',
        'local.pingtung.flood_sensor',
        'official',
        'Government Open Data License',
        'near_realtime',
        'unknown',
        'L3',
        false,
        jsonb_build_object(
            'label_zh', '屏東縣地方淹水感測器',
            'owner_authority', 'Pingtung County Government',
            'license_name', 'Government Open Data License',
            'tier', 'L3',
            'source_url', 'https://www.dprcflood.org.tw/SGDS/',
            'resource_url', 'https://www.dprcflood.org.tw/SGDS/WS/FHYBrokerWS.asmx/GetFHYFloodSensorInfoRt',
            'station_resource_url', 'https://www.dprcflood.org.tw/SGDS/WS/FHYBrokerWS.asmx/GetFHYFloodSensorStationByCityCode',
            'city_code', 10013,
            'supplier_filter', '屏東縣政府',
            'notes', 'Disabled by default; reads public FHY broker realtime rows joined to CityCode 10013 station metadata, keeping only Supplier=屏東縣政府.',
            'review_status', 'ready',
            'phase', 'local_realtime_sources'
        )
    ),
    (
        'Hualien local FHY flood sensor observations',
        'local.hualien.flood_sensor',
        'official',
        'Government Open Data License',
        'near_realtime',
        'unknown',
        'L3',
        false,
        jsonb_build_object(
            'label_zh', '花蓮縣地方淹水感測器',
            'owner_authority', 'Hualien County Government',
            'license_name', 'Government Open Data License',
            'tier', 'L3',
            'source_url', 'https://www.dprcflood.org.tw/SGDS/',
            'resource_url', 'https://www.dprcflood.org.tw/SGDS/WS/FHYBrokerWS.asmx/GetFHYFloodSensorInfoRt',
            'station_resource_url', 'https://www.dprcflood.org.tw/SGDS/WS/FHYBrokerWS.asmx/GetFHYFloodSensorStationByCityCode',
            'city_code', 10015,
            'supplier_filter', '花蓮縣政府',
            'notes', 'Disabled by default; reads public FHY broker realtime rows joined to CityCode 10015 station metadata, keeping only Supplier=花蓮縣政府. The richer Senslink dashboard remains authorization-gated.',
            'review_status', 'ready',
            'phase', 'local_realtime_sources'
        )
    ),
    (
        'Taitung local FHY flood sensor observations',
        'local.taitung.flood_sensor',
        'official',
        'Government Open Data License',
        'near_realtime',
        'unknown',
        'L3',
        false,
        jsonb_build_object(
            'label_zh', '臺東縣地方淹水感測器',
            'owner_authority', 'Taitung County Government',
            'license_name', 'Government Open Data License',
            'tier', 'L3',
            'source_url', 'https://www.dprcflood.org.tw/SGDS/',
            'resource_url', 'https://www.dprcflood.org.tw/SGDS/WS/FHYBrokerWS.asmx/GetFHYFloodSensorInfoRt',
            'station_resource_url', 'https://www.dprcflood.org.tw/SGDS/WS/FHYBrokerWS.asmx/GetFHYFloodSensorStationByCityCode',
            'city_code', 10014,
            'supplier_filter', '臺東縣政府',
            'notes', 'Disabled by default; reads public FHY broker realtime rows joined to CityCode 10014 station metadata, keeping only Supplier=臺東縣政府 or 台東縣政府.',
            'review_status', 'ready',
            'phase', 'local_realtime_sources'
        )
    )
ON CONFLICT (adapter_key) DO UPDATE SET
    name = EXCLUDED.name,
    source_type = EXCLUDED.source_type,
    license = EXCLUDED.license,
    update_frequency = EXCLUDED.update_frequency,
    health_status = EXCLUDED.health_status,
    legal_basis = EXCLUDED.legal_basis,
    is_enabled = EXCLUDED.is_enabled,
    metadata = data_sources.metadata || EXCLUDED.metadata,
    updated_at = now();
