"""Local-government flood sensors exposed through the public FHY broker."""

from app.adapters.local_fhy.flood_sensor import (
    CHANGHUA_FHY_FLOOD_SENSOR,
    DEFAULT_FHY_FLOOD_SENSOR_TIMEOUT_SECONDS,
    FHY_DATA_URL,
    FHY_FLOOD_SENSOR_REALTIME_API_URL,
    FHY_FLOOD_SENSOR_STATION_API_URL,
    FHY_LOCAL_FLOOD_SENSOR_SOURCES,
    HSINCHU_COUNTY_FHY_FLOOD_SENSOR,
    HUALIEN_FHY_FLOOD_SENSOR,
    MIAOLI_FHY_FLOOD_SENSOR,
    PINGTUNG_FHY_FLOOD_SENSOR,
    TAITUNG_FHY_FLOOD_SENSOR,
    FetchJson,
    FhyFloodSensorAdapterError,
    FhyFloodSensorApiAdapter,
    FhyFloodSensorFetchError,
    FhyFloodSensorPayloadError,
    FhyFloodSensorSource,
    fetch_fhy_json,
    parse_fhy_flood_sensor_realtime_payload,
    parse_fhy_flood_sensor_station_payload,
)

__all__ = [
    "CHANGHUA_FHY_FLOOD_SENSOR",
    "DEFAULT_FHY_FLOOD_SENSOR_TIMEOUT_SECONDS",
    "FHY_DATA_URL",
    "FHY_FLOOD_SENSOR_REALTIME_API_URL",
    "FHY_FLOOD_SENSOR_STATION_API_URL",
    "FHY_LOCAL_FLOOD_SENSOR_SOURCES",
    "HSINCHU_COUNTY_FHY_FLOOD_SENSOR",
    "HUALIEN_FHY_FLOOD_SENSOR",
    "MIAOLI_FHY_FLOOD_SENSOR",
    "PINGTUNG_FHY_FLOOD_SENSOR",
    "TAITUNG_FHY_FLOOD_SENSOR",
    "FetchJson",
    "FhyFloodSensorAdapterError",
    "FhyFloodSensorApiAdapter",
    "FhyFloodSensorFetchError",
    "FhyFloodSensorPayloadError",
    "FhyFloodSensorSource",
    "fetch_fhy_json",
    "parse_fhy_flood_sensor_realtime_payload",
    "parse_fhy_flood_sensor_station_payload",
]
