"""Hsinchu City local official water adapters."""

from app.adapters.local_hsinchu_city.water import (
    DEFAULT_HSINCHU_CITY_WATER_TIMEOUT_SECONDS,
    HSINCHU_CITY_FLOOD_SENSOR_DATA_URL,
    HSINCHU_CITY_FLOOD_SENSOR_METADATA,
    HSINCHU_CITY_FLOOD_SENSOR_REALTIME_API_URL,
    HSINCHU_CITY_FLOOD_SENSOR_STATION_API_URL,
    HSINCHU_CITY_SEWER_BASE_API_URL,
    HSINCHU_CITY_SEWER_DATA_URL,
    HSINCHU_CITY_SEWER_REALTIME_API_URL,
    HSINCHU_CITY_SEWER_WATER_LEVEL_METADATA,
    FetchJson,
    HsinchuCityFloodSensorApiAdapter,
    HsinchuCitySewerWaterLevelApiAdapter,
    HsinchuCityWaterAdapterError,
    HsinchuCityWaterFetchError,
    HsinchuCityWaterPayloadError,
    fetch_hsinchu_city_json,
    parse_hsinchu_city_flood_sensor_realtime_payload,
    parse_hsinchu_city_flood_sensor_station_payload,
    parse_hsinchu_city_sewer_payload,
)

__all__ = [
    "DEFAULT_HSINCHU_CITY_WATER_TIMEOUT_SECONDS",
    "HSINCHU_CITY_FLOOD_SENSOR_DATA_URL",
    "HSINCHU_CITY_FLOOD_SENSOR_METADATA",
    "HSINCHU_CITY_FLOOD_SENSOR_REALTIME_API_URL",
    "HSINCHU_CITY_FLOOD_SENSOR_STATION_API_URL",
    "HSINCHU_CITY_SEWER_BASE_API_URL",
    "HSINCHU_CITY_SEWER_DATA_URL",
    "HSINCHU_CITY_SEWER_REALTIME_API_URL",
    "HSINCHU_CITY_SEWER_WATER_LEVEL_METADATA",
    "FetchJson",
    "HsinchuCityFloodSensorApiAdapter",
    "HsinchuCitySewerWaterLevelApiAdapter",
    "HsinchuCityWaterAdapterError",
    "HsinchuCityWaterFetchError",
    "HsinchuCityWaterPayloadError",
    "fetch_hsinchu_city_json",
    "parse_hsinchu_city_flood_sensor_realtime_payload",
    "parse_hsinchu_city_flood_sensor_station_payload",
    "parse_hsinchu_city_sewer_payload",
]
